/**
 * Road Traffic Fine Categories
 * Organizes fines by road_category field from JSON data
 */

export interface RoadCategory {
  id: string;
  displayName: {
    en: string;
    de: string;
    fr: string;
    it: string;
    es: string;
    pt: string;
    tr: string;
    [key: string]: string;
  };
  description: {
    en: string;
    de: string;
    fr: string;
    it: string;
    es: string;
    pt: string;
    tr: string;
    [key: string]: string;
  };
  filters: string[]; // Maps to road_category values in JSON
  icon: string; // Ionicons name
  color: string; // Hex color for card tint
}

export const ROAD_CATEGORIES: RoadCategory[] = [
  {
    id: 'vehicle-docs',
    displayName: {
      en: 'Vehicle & Documents',
      de: 'Fahrzeug & Dokumente',
      fr: 'Véhicule et documents',
      it: 'Veicolo e documenti',
      es: 'Vehículo y documentos',
      pt: 'Veículo e documentos',
      tr: 'Araç ve Belgeler',
      ro: 'Vehicul și documente',
      pl: 'Pojazd i dokumenty',
      sq: 'Automjeti dhe dokumentet',
      bg: 'Превозно средство и документи',
      cs: 'Vozidlo a dokumenty',
      sk: 'Vozidlo a dokumenty',
      hu: 'Jármű és dokumentumok',
      hr: 'Vozilo i dokumenti',
      sr: 'Vozilo i dokumenti',
      bs: 'Vozilo i dokumenti',
      me: 'Vozilo i dokumenti',
    },
    description: {
      en: 'License, Registration, Permits',
      de: 'Führerschein, Zulassung, Genehmigungen',
      fr: 'Permis, immatriculation, autorisations',
      it: 'Patente, immatricolazione, permessi',
      es: 'Licencia, registro, permisos',
      pt: 'Licença, registro, autorizações',
      tr: 'Ehliyet, kayıt, izinler',
      ro: 'Permis, înmatriculare, autorizații',
      pl: 'Prawo jazdy, rejestracja, zezwolenia',
      sq: 'Licencë, regjistrim, leje',
      bg: 'Книжка, регистрация, разрешения',
      cs: 'Řidičák, registrace, povolení',
      sk: 'Vodičák, registrácia, povolenia',
      hu: 'Jogosítvány, regisztráció, engedélyek',
      hr: 'Vozačka dozvola, registracija, dozvole',
      sr: 'Vozačka dozvola, registracija, dozvole',
      bs: 'Vozačka dozvola, registracija, dozvole',
      me: 'Vozačka dozvola, registracija, dozvole',
    },
    filters: ['vehicle-docs', 'paperwork'],
    icon: 'document-text',
    color: '#4A90E2', // Blue
  },
  {
    id: 'professional-driver',
    displayName: {
      en: 'Professional Drivers',
      de: 'Berufsfahrer',
      fr: 'Conducteurs professionnels',
      it: 'Conducenti professionali',
      es: 'Conductores profesionales',
      pt: 'Condutores profissionais',
      tr: 'Profesyonel sürücüler',
      ro: 'Șoferi profesioniști',
      pl: 'Kierowcy zawodowi',
      sq: 'Shoferë profesionistë',
      bg: 'Професионални шофьори',
      cs: 'Profesionální řidiči',
      sk: 'Profesionálni vodiči',
      hu: 'Hivatásos sofőrök',
      hr: 'Profesionalni vozači',
      sr: 'Profesionalni vozači',
      bs: 'Profesionalni vozači',
      me: 'Profesionalni vozači',
    },
    description: {
      en: 'Tachograph, Work Hours, Taxi',
      de: 'Fahrtenschreiber, Arbeitszeiten, Taxi',
      fr: 'Tachygraphe, heures de travail, taxi',
      it: 'Tachigrafo, orari di lavoro, taxi',
      es: 'Tacógrafo, horas de trabajo, taxi',
      pt: 'Tacógrafo, horas de trabalho, táxi',
      tr: 'Takoğraf, çalışma saatleri, taksi',
      ro: 'Tahograf, ore de muncă, taxi',
      pl: 'Tachograf, godziny pracy, taksówka',
      sq: 'Takograf, orë pune, taksi',
      bg: 'Тахограф, работно време, такси',
      cs: 'Tachograf, pracovní doba, taxi',
      sk: 'Tachograf, pracovný čas, taxi',
      hu: 'Tachográf, munkaidő, taxi',
      hr: 'Tahograf, radno vreme, taksi',
      sr: 'Tahograf, radno vreme, taksi',
      bs: 'Tahograf, radno vreme, taksi',
      me: 'Tahograf, radno vreme, taksi',
    },
    filters: ['professional-driver', 'taxi/uber'],
    icon: 'briefcase',
    color: '#7B68EE', // Purple
  },
  {
    id: 'parking',
    displayName: {
      en: 'Parking',
      de: 'Parkieren',
      fr: 'Stationnement',
      it: 'Parcheggio',
      es: 'Estacionamiento',
      pt: 'Estacionamento',
      tr: 'Park etme',
      ro: 'Parcare',
      pl: 'Parkowanie',
      sq: 'Parkimi',
      bg: 'Паркиране',
      cs: 'Parkování',
      sk: 'Parkovanie',
      hu: 'Parkolás',
      hr: 'Parkiranje',
      sr: 'Parkiranje',
      bs: 'Parkiranje',
      me: 'Parkiranje',
    },
    description: {
      en: 'Parking Violations & Rules',
      de: 'Parkverstöße & Regeln',
      fr: 'Infractions et règles de stationnement',
      it: 'Violazioni e regole di parcheggio',
      es: 'Infracciones y reglas de estacionamiento',
      pt: 'Violações e regras de estacionamento',
      tr: 'Park ihlalleri ve kuralları',
      ro: 'Încălcări și reguli de parcare',
      pl: 'Naruszenia i zasady parkowania',
      sq: 'Shkeljet dhe rregullat e parkimit',
      bg: 'Нарушения и правила за паркиране',
      cs: 'Porušení a pravidla parkování',
      sk: 'Porušenia a pravidlá parkovania',
      hu: 'Parkolási szabálysértések és szabályok',
      hr: 'Prekršaji i pravila parkiranja',
      sr: 'Prekršaji i pravila parkiranja',
      bs: 'Prekršaji i pravila parkiranja',
      me: 'Prekršaji i pravila parkiranja',
    },
    filters: ['parking'],
    icon: 'car',
    color: '#26A69A', // Teal
  },
  {
    id: 'speeding',
    displayName: {
      en: 'Speeding',
      de: 'Geschwindigkeit',
      fr: 'Excès de vitesse',
      it: 'Eccesso di velocità',
      es: 'Exceso de velocidad',
      pt: 'Excesso de velocidade',
      tr: 'Hız aşımı',
      ro: 'Exces de viteză',
      pl: 'Przekroczenie prędkości',
      sq: 'Shpejtësi',
      bg: 'Превишена скорост',
      cs: 'Překročení rychlosti',
      sk: 'Prekročenie rýchlosti',
      hu: 'Gyorshajtás',
      hr: 'Prekoračenje brzine',
      sr: 'Prekoračenje brzine',
      bs: 'Prekoračenje brzine',
      me: 'Prekoračenje brzine',
    },
    description: {
      en: 'Speed Limit Violations',
      de: 'Geschwindigkeitsüberschreitungen',
      fr: 'Violations de limite de vitesse',
      it: 'Violazioni del limite di velocità',
      es: 'Violaciones del límite de velocidad',
      pt: 'Violações do limite de velocidade',
      tr: 'Hız sınırı ihlalleri',
      ro: 'Încălcări ale limitei de viteză',
      pl: 'Naruszenia ograniczenia prędkości',
      sq: 'Shkeljet e kufirit të shpejtësisë',
      bg: 'Нарушения на ограничението на скоростта',
      cs: 'Porušení rychlostního limitu',
      sk: 'Porušenia rýchlostného limitu',
      hu: 'Sebességkorlátozás túllépése',
      hr: 'Prekršaji ograničenja brzine',
      sr: 'Prekršaji ograničenja brzine',
      bs: 'Prekršaji ograničenja brzine',
      me: 'Prekršaji ograničenja brzine',
    },
    filters: ['speeding'],
    icon: 'speedometer',
    color: '#E53935', // Red
  },
  {
    id: 'signaling',
    displayName: {
      en: 'Signs & Signals',
      de: 'Signale & Zeichen',
      fr: 'Signaux et panneaux',
      it: 'Segnali e cartelli',
      es: 'Señales y señalización',
      pt: 'Sinais e sinalização',
      tr: 'İşaretler ve sinyaller',
      ro: 'Semne și semnale',
      pl: 'Znaki i sygnały',
      sq: 'Shenjat dhe sinjalet',
      bg: 'Знаци и сигнали',
      cs: 'Značky a signály',
      sk: 'Značky a signály',
      hu: 'Jelzések és táblák',
      hr: 'Znakovi i signali',
      sr: 'Znakovi i signali',
      bs: 'Znakovi i signali',
      me: 'Znakovi i signali',
    },
    description: {
      en: 'Traffic Signs, Lights, Signals',
      de: 'Verkehrsschilder, Ampeln, Signale',
      fr: 'Panneaux, feux, signaux',
      it: 'Segnali stradali, semafori, segnali',
      es: 'Señales de tráfico, luces, señales',
      pt: 'Sinais de trânsito, semáforos, sinais',
      tr: 'Trafik işaretleri, ışıklar, sinyaller',
      ro: 'Semne de circulație, semafoare, semnale',
      pl: 'Znaki drogowe, światła, sygnały',
      sq: 'Shenjat rrugore, dritat, sinjalet',
      bg: 'Пътни знаци, светлини, сигнали',
      cs: 'Dopravní značky, světla, signály',
      sk: 'Dopravné značky, svetlá, signály',
      hu: 'Közlekedési táblák, lámpák, jelzések',
      hr: 'Saobraćajni znakovi, svetla, signali',
      sr: 'Saobraćajni znakovi, svetla, signali',
      bs: 'Saobraćajni znakovi, svetla, signali',
      me: 'Saobraćajni znakovi, svetla, signali',
    },
    filters: ['signaling'],
    icon: 'warning',
    color: '#FF9800', // Orange
  },
  {
    id: 'equipment',
    displayName: {
      en: 'Equipment',
      de: 'Ausrüstung',
      fr: 'Équipement',
      it: 'Equipaggiamento',
      es: 'Equipamiento',
      pt: 'Equipamento',
      tr: 'Ekipman',
      ro: 'Echipament',
      pl: 'Wyposażenie',
      sq: 'Pajisjet',
      bg: 'Оборудване',
      cs: 'Vybavení',
      sk: 'Vybavenie',
      hu: 'Felszerelés',
      hr: 'Oprema',
      sr: 'Oprema',
      bs: 'Oprema',
      me: 'Oprema',
    },
    description: {
      en: 'Lights, Mirrors, Safety Gear',
      de: 'Lichter, Spiegel, Sicherheitsausrüstung',
      fr: 'Éclairage, rétroviseurs, équipement de sécurité',
      it: 'Luci, specchietti, attrezzatura di sicurezza',
      es: 'Luces, espejos, equipo de seguridad',
      pt: 'Luzes, espelhos, equipamento de segurança',
      tr: 'Işıklar, aynalar, güvenlik ekipmanı',
      ro: 'Lumini, oglinzi, echipament de siguranță',
      pl: 'Światła, lusterka, sprzęt bezpieczeństwa',
      sq: 'Dritat, pasqyrat, pajisjet e sigurisë',
      bg: 'Светлини, огледала, оборудване за безопасност',
      cs: 'Světla, zrcátka, bezpečnostní vybavení',
      sk: 'Svetlá, zrkadlá, bezpečnostné vybavenie',
      hu: 'Lámpák, tükrök, biztonsági felszerelés',
      hr: 'Svetla, ogledala, sigurnosna oprema',
      sr: 'Svetla, ogledala, sigurnosna oprema',
      bs: 'Svetla, ogledala, sigurnosna oprema',
      me: 'Svetla, ogledala, sigurnosna oprema',
    },
    filters: ['equipment'],
    icon: 'build',
    color: '#8D6E63', // Brown
  },
  {
    id: 'driver-behavior',
    displayName: {
      en: 'Driver Behavior',
      de: 'Fahrverhalten',
      fr: 'Comportement du conducteur',
      it: 'Comportamento del conducente',
      es: 'Comportamiento del conductor',
      pt: 'Comportamento do condutor',
      tr: 'Sürücü davranışı',
      ro: 'Comportamentul șoferului',
      pl: 'Zachowanie kierowcy',
      sq: 'Sjellja e shoferit',
      bg: 'Поведение на водача',
      cs: 'Chování řidiče',
      sk: 'Správanie vodiča',
      hu: 'Vezető magatartása',
      hr: 'Ponašanje vozača',
      sr: 'Ponašanje vozača',
      bs: 'Ponašanje vozača',
      me: 'Ponašanje vozača',
    },
    description: {
      en: 'General Driving Violations',
      de: 'Allgemeine Fahrverstöße',
      fr: 'Infractions générales de conduite',
      it: 'Violazioni generali di guida',
      es: 'Infracciones generales de conducción',
      pt: 'Violações gerais de condução',
      tr: 'Genel sürüş ihlalleri',
      ro: 'Încălcări generale de conducere',
      pl: 'Ogólne naruszenia jazdy',
      sq: 'Shkeljet e përgjithshme të drejtimit',
      bg: 'Общи нарушения при шофиране',
      cs: 'Obecná porušení řízení',
      sk: 'Všeobecné porušenia jazdy',
      hu: 'Általános vezetési szabálysértések',
      hr: 'Opšti prekršaji vožnje',
      sr: 'Opšti prekršaji vožnje',
      bs: 'Opšti prekršaji vožnje',
      me: 'Opšti prekršaji vožnje',
    },
    filters: ['driver'],
    icon: 'person',
    color: '#5C6BC0', // Indigo
  },
  {
    id: 'other-road',
    displayName: {
      en: 'Other Road Rules',
      de: 'Sonstige Verkehrsregeln',
      fr: 'Autres règles routières',
      it: 'Altre regole stradali',
      es: 'Otras reglas de tráfico',
      pt: 'Outras regras de trânsito',
      tr: 'Diğer trafik kuralları',
      ro: 'Alte reguli rutiere',
      pl: 'Inne zasady ruchu',
      sq: 'Rregulla të tjera rrugore',
      bg: 'Други правила за движение',
      cs: 'Jiná pravidla silničního provozu',
      sk: 'Iné pravidlá cestnej premávky',
      hu: 'Egyéb közlekedési szabályok',
      hr: 'Ostala saobraćajna pravila',
      sr: 'Ostala saobraćajna pravila',
      bs: 'Ostala saobraćajna pravila',
      me: 'Ostala saobraćajna pravila',
    },
    description: {
      en: 'Miscellaneous Traffic Rules',
      de: 'Verschiedene Verkehrsregeln',
      fr: 'Règles de circulation diverses',
      it: 'Regole di traffico varie',
      es: 'Reglas de tráfico diversas',
      pt: 'Regras de trânsito diversas',
      tr: 'Çeşitli trafik kuralları',
      ro: 'Reguli de circulație diverse',
      pl: 'Różne zasady ruchu',
      sq: 'Rregulla të ndryshme të trafikut',
      bg: 'Различни правила за движение',
      cs: 'Různá pravidla silničního provozu',
      sk: 'Rôzne pravidlá cestnej premávky',
      hu: 'Különféle közlekedési szabályok',
      hr: 'Razna saobraćajna pravila',
      sr: 'Razna saobraćajna pravila',
      bs: 'Razna saobraćajna pravila',
      me: 'Razna saobraćajna pravila',
    },
    filters: ['other-road'],
    icon: 'trail-sign',
    color: '#78909C', // Blue Grey
  },
];
